import {
  FaAndroid,
  FaAngular,
  FaAws,
  FaBitbucket,
  FaBootstrap,
  FaDocker,
  FaGitAlt,
  FaHtml5,
  FaJava,
  FaNodeJs,
  FaPhp,
  FaReact,
  FaSymfony,
  FaVuejs,
  FaWordpress,
} from 'react-icons/fa';
import { FaCss, FaFlutter, FaSquareGitlab, FaUnity } from 'react-icons/fa6';
import { TbBrandCSharp, TbBrandReactNative } from 'react-icons/tb';
import { AiOutlineDotNet } from 'react-icons/ai';
import { IoLogoJavascript } from 'react-icons/io5';
import { DiJqueryLogo, DiMysql, DiPostgresql } from 'react-icons/di';
import {
  SiDart,
  SiJetpackcompose,
  SiJira,
  SiKotlin,
  SiMongodb,
  SiNestjs,
  SiOdoo,
  SiOpencode,
  SiSpringboot,
  SiSqlite,
  SiSubversion,
  SiTypescript,
} from 'react-icons/si';
import { LuCodeXml } from 'react-icons/lu';

import type { TechId, Technology } from '@/interfaces';

export const TECHNOLOGIES: Record<TechId, Technology> = {
  android: {
    id: 'android',
    name: 'Android',
    icon: FaAndroid,
    color: '',
    category: 'platform',
    areas: ['mobile'],
  },
  angular: {
    id: 'angular',
    name: 'Angular',
    icon: FaAngular,
    color: '',
    category: 'framework',
    areas: ['frontend'],
  },
  aws: {
    id: 'aws',
    name: 'AWS',
    icon: FaAws,
    color: '',
    category: 'platform',
    areas: ['backend', 'devops'],
  },
  bitbucket: {
    id: 'bitbucket',
    name: 'Bitbucket',
    icon: FaBitbucket,
    color: '',
    category: 'tool',
    areas: ['general', 'devops'],
  },
  bloc: {
    id: 'bloc',
    name: 'BLoC',
    color: '',
    category: 'state-management',
    areas: ['mobile'],
  },
  bootstrap: {
    id: 'bootstrap',
    name: 'Bootstrap',
    icon: FaBootstrap,
    color: '',
    category: 'library',
    areas: ['frontend'],
  },
  'c-sharp': {
    id: 'c-sharp',
    name: 'C#',
    icon: TbBrandCSharp,
    color: '',
    category: 'language',
    areas: ['backend', 'game-development'],
  },
  css: {
    id: 'css',
    name: 'CSS',
    icon: FaCss,
    color: '',
    category: 'markup',
    areas: ['frontend'],
  },
  dart: {
    id: 'dart',
    name: 'Dart',
    icon: SiDart,
    color: '',
    category: 'language',
    areas: ['mobile', 'frontend'],
  },
  docker: {
    id: 'docker',
    name: 'Docker',
    icon: FaDocker,
    color: '',
    category: 'tool',
    areas: ['devops', 'general'],
  },
  'dot-net': {
    id: 'dot-net',
    name: '.NET',
    icon: AiOutlineDotNet,
    color: '',
    category: 'framework',
    areas: ['backend'],
  },
  flutter: {
    id: 'flutter',
    name: 'Flutter',
    icon: FaFlutter,
    color: '',
    category: 'framework',
    areas: ['mobile', 'frontend'],
  },
  git: {
    id: 'git',
    name: 'Git',
    icon: FaGitAlt,
    color: '',
    category: 'version-control',
    areas: ['devops', 'general'],
  },
  'git-flow': {
    id: 'git-flow',
    name: 'Git Flow',
    category: 'version-control',
    areas: ['general'],
  },
  gitlab: {
    id: 'gitlab',
    name: 'GitLab',
    icon: FaSquareGitlab,
    color: '',
    category: 'version-control',
    areas: ['devops', 'general'],
  },
  html: {
    id: 'html',
    name: 'HTML',
    icon: FaHtml5,
    color: '',
    category: 'markup',
    areas: ['frontend'],
  },
  java: {
    id: 'java',
    name: 'Java',
    icon: FaJava,
    color: '',
    category: 'language',
    areas: ['backend'],
  },
  javascript: {
    id: 'javascript',
    name: 'JavaScript',
    icon: IoLogoJavascript,
    color: '',
    category: 'language',
    areas: ['backend', 'frontend', 'mobile'],
  },
  'jetpack-compose': {
    id: 'jetpack-compose',
    name: 'Jetpack Compose',
    icon: SiJetpackcompose,
    color: '',
    category: 'ui-toolkit',
    areas: ['mobile'],
  },
  jira: {
    id: 'jira',
    name: 'Jira',
    icon: SiJira,
    color: '',
    category: 'tool',
    areas: ['general'],
  },
  jquery: {
    id: 'jquery',
    name: 'jQuery',
    icon: DiJqueryLogo,
    color: '',
    category: 'library',
    areas: ['frontend'],
  },
  kotlin: {
    id: 'kotlin',
    name: 'Kotlin',
    icon: SiKotlin,
    color: '',
    category: 'language',
    areas: ['backend', 'mobile'],
  },
  'material-3': {
    id: 'material-3',
    name: 'Material 3',
    color: '',
    category: 'ui-toolkit',
    areas: ['frontend', 'mobile'],
  },
  mongodb: {
    id: 'mongodb',
    name: 'MongoDB',
    icon: SiMongodb,
    color: '',
    category: 'database',
    areas: ['database-non-relational', 'backend'],
  },
  mysql: {
    id: 'mysql',
    name: 'MySQL',
    icon: DiMysql,
    color: '',
    category: 'database',
    areas: ['database-relational', 'backend'],
  },
  nestjs: {
    id: 'nestjs',
    name: 'Nest.js',
    icon: SiNestjs,
    color: '',
    category: 'framework',
    areas: ['backend'],
  },
  nodejs: {
    id: 'nodejs',
    name: 'Node.js',
    icon: FaNodeJs,
    color: '',
    category: 'platform',
    areas: ['backend'],
  },
  odoo: {
    id: 'odoo',
    name: 'Odoo',
    icon: SiOdoo,
    color: '',
    category: 'erp',
    areas: ['general'],
  },
  opencode: {
    id: 'opencode',
    name: 'OpenCode',
    icon: SiOpencode,
    color: '',
    category: 'tool',
    areas: ['general'],
  },
  php: {
    id: 'php',
    name: 'PHP',
    icon: FaPhp,
    color: '',
    category: 'language',
    areas: ['backend'],
  },
  postgresql: {
    id: 'postgresql',
    name: 'PostgreSQL',
    icon: DiPostgresql,
    color: '',
    category: 'database',
    areas: ['database-relational', 'backend'],
  },
  'react-native': {
    id: 'react-native',
    name: 'React Native',
    icon: TbBrandReactNative,
    color: '',
    category: 'framework',
    areas: ['mobile'],
  },
  react: {
    id: 'react',
    name: 'React',
    icon: FaReact,
    color: '',
    category: 'library',
    areas: ['frontend'],
  },
  room: {
    id: 'room',
    name: 'Room',
    color: '',
    category: 'database',
    areas: ['database-relational', 'mobile'],
  },
  'spring-boot': {
    id: 'spring-boot',
    name: 'Spring Boot',
    icon: SiSpringboot,
    color: '',
    category: 'framework',
    areas: ['backend'],
  },
  sqlite: {
    id: 'sqlite',
    name: 'SQLite',
    icon: SiSqlite,
    color: '',
    category: 'database',
    areas: ['database-relational', 'backend', 'mobile'],
  },
  subversion: {
    id: 'subversion',
    name: 'Subversion',
    icon: SiSubversion,
    color: '',
    category: 'version-control',
    areas: ['general'],
  },
  symfony: {
    id: 'symfony',
    name: 'Symfony',
    icon: FaSymfony,
    color: '',
    category: 'framework',
    areas: ['backend'],
  },
  typescript: {
    id: 'typescript',
    name: 'TypeScript',
    icon: SiTypescript,
    color: '',
    category: 'language',
    areas: ['backend', 'frontend', 'mobile'],
  },
  unity: {
    id: 'unity',
    name: 'Unity',
    icon: FaUnity,
    color: '',
    category: 'game-engine',
    areas: ['game-development'],
  },
  vue: {
    id: 'vue',
    name: 'Vue',
    icon: FaVuejs,
    color: '',
    category: 'framework',
    areas: ['frontend'],
  },
  wordpress: {
    id: 'wordpress',
    name: 'WordPress',
    icon: FaWordpress,
    color: '',
    category: 'cms',
    areas: ['general'],
  },
  xml: {
    id: 'xml',
    name: 'XML',
    icon: LuCodeXml,
    color: '',
    category: 'markup',
    areas: ['general'],
  },
  zustand: {
    id: 'zustand',
    name: 'Zustand',
    color: '',
    category: 'state-management',
    areas: ['frontend'],
  },
};
